### Get Token
POST http://localhost:8080/auth/login 
Content-Type: application/json

{
  "id": "kido",
  "username": "admin",
  "password": "passwd" 
}

### Refresh Token
POST http://localhost:8080/auth/refresh
Content-Type: application/json

{
  "refresh_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2MTk0MzY1NjEsInVzZXJfaWQiOiJraWRvIn0.8OGNCarRqdte1FAtU1sM5RhDBy4Ri6OBdRJkF2XNrlQ"
}